### ISSUE TITLE
Update dependency: jtskit --> jsontableschema

### ISSUE THREAD

**Issue by brew** [okfn/goodtables#61] opened 2015-11-03 14:49 UTC
Once jsontableschema 0.5.0 is available, the jtskit dependency should be changed to jsontableschema.

Some hints where it's used and defined in goodtables: https://github.com/okfn/goodtables/search?utf8=%E2%9C%93&q=jtskit

**Comment by augusto-herrmann** [comment] 2016-01-29 02:25
Goodtables v0.5.6 is unusable because of this bug.

Steps to reproduce:

```
$ pip install goodtables

...

$ goodtables
...
  File "... /local/lib/python2.7/site-packages/goodtables/processors/schema.py", line 7, in <module>
    import jtskit
ImportError: No module named jtskit
```

Attempting to install jtskit manually does not solve it:

```
$ pip install jtskit
Requirement already satisfied (use --upgrade to upgrade): jtskit in ./pyenv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): jsontableschema>=0.5.1 in ./pyenv/lib/python2.7/site-packages (from jtskit)
Cleaning up...
```

I suppose the only solution, for now, is probably using goodtables from the latest commit from the repository. Simply using stable versions with pip is not currently possible.

**Comment by brew** [comment] 2016-01-29 09:41
@pwalsh Does this just need a new release of Goodtables to pypi?

**Comment by pwalsh** [comment] 2016-01-29 11:58
@brew not sure and can't check now. *if* you have time to check (and push) would be great.

**Comment by augusto-herrmann** [comment] 2016-01-29 18:48
I think so. When I installed it last night by using `git clone` (from master) and then `pip install -U .`, the CLI worked.

**Comment by pwalsh** [comment] 2016-02-18 14:37
Fixed in `0.6.0` https://github.com/okfn/goodtables/tree/0.6.0

**Closed by pwalsh** 2016-02-18 14:37 UTC
Labels: bug
